-- >>TABLE 参数定义表
CREATE TABLE MYDMS_PARAMETER
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  TYPE VARCHAR2(4000) NOT NULL,
  VALID NUMBER(9),
  ATTACH_COUNT NUMBER(9) NOT NULL,
  ATTACH_SIZE NUMBER(18),
  CREATOR VARCHAR2(32),
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_PARAMETER.OID IS 'OID';
COMMENT ON COLUMN MYDMS_PARAMETER.NAME IS '名称';
COMMENT ON COLUMN MYDMS_PARAMETER.DESCRIPTION IS '描述';
COMMENT ON COLUMN MYDMS_PARAMETER.TYPE IS '允许上传的文件类型';
COMMENT ON COLUMN MYDMS_PARAMETER.VALID IS '有效与否 0:无效, 1:有效';
COMMENT ON COLUMN MYDMS_PARAMETER.ATTACH_COUNT IS '限制附件个数';
COMMENT ON COLUMN MYDMS_PARAMETER.ATTACH_SIZE IS '单个附件大小';
COMMENT ON COLUMN MYDMS_PARAMETER.CREATOR IS '创建者';
COMMENT ON COLUMN MYDMS_PARAMETER.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_PARAMETER IS '参数定义表';



-- >>TABLE 自动编号定义表
CREATE TABLE MYDMS_SNRULEDEF
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  PARAMETER1 VARCHAR2(50),
  DELIMITER1 VARCHAR2(50),
  PARAMETER2 VARCHAR2(50),
  DELIMITER2 VARCHAR2(50),
  PARAMETER3 VARCHAR2(50),
  DELIMITER3 VARCHAR2(50),
  QUANTITY NUMBER(9),
  DESCRIPTION VARCHAR2(4000),
  VALID NUMBER(9),
  CREATOR VARCHAR2(32),
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_SNRULEDEF.OID IS 'OID';
COMMENT ON COLUMN MYDMS_SNRULEDEF.NAME IS '规则名称';
COMMENT ON COLUMN MYDMS_SNRULEDEF.PARAMETER1 IS '分类参数1';
COMMENT ON COLUMN MYDMS_SNRULEDEF.DELIMITER1 IS '分割符1';
COMMENT ON COLUMN MYDMS_SNRULEDEF.PARAMETER2 IS '分类参数2';
COMMENT ON COLUMN MYDMS_SNRULEDEF.DELIMITER2 IS '分割符2';
COMMENT ON COLUMN MYDMS_SNRULEDEF.PARAMETER3 IS '分类参数3';
COMMENT ON COLUMN MYDMS_SNRULEDEF.DELIMITER3 IS '分割符3';
COMMENT ON COLUMN MYDMS_SNRULEDEF.QUANTITY IS '流水号位数';
COMMENT ON COLUMN MYDMS_SNRULEDEF.DESCRIPTION IS '说明';
COMMENT ON COLUMN MYDMS_SNRULEDEF.VALID IS '有效与否 0:无效, 1:有效';
COMMENT ON COLUMN MYDMS_SNRULEDEF.CREATOR IS '创建者';
COMMENT ON COLUMN MYDMS_SNRULEDEF.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_SNRULEDEF IS '自动编号定义表';



-- >>TABLE 文件编号流水号记录表
CREATE TABLE MYDMS_SNTEMP
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  SNRULEDEF CHAR(32) NOT NULL,
  SNPREFIX VARCHAR2(400) NOT NULL,
  NUM NUMBER(18),
  CREATEDATE DATE DEFAULT SYSDATE
  -- CONSTRAINT FK_SNTEMP_SNRULEDEF FOREIGN KEY (SNRULEDEF) REFERENCES MYDMS_SNRULEDEF (OID),
  -- CONSTRAINT FK_SNTEMP_DOCUMENT FOREIGN KEY (DOCUMENT) REFERENCES MYDMS_DOCUMENT (OID)
);
COMMENT ON COLUMN MYDMS_SNTEMP.OID IS 'OID';
COMMENT ON COLUMN MYDMS_SNTEMP.SNRULEDEF IS '自动编码规则OID';
COMMENT ON COLUMN MYDMS_SNTEMP.SNPREFIX IS '流水号前缀';
COMMENT ON COLUMN MYDMS_SNTEMP.NUM IS '该系列流水号目前最大自增长值';
COMMENT ON COLUMN MYDMS_SNTEMP.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_SNTEMP IS '文件编号流水号记录表';



  -- >>TABLE 自动版号定义表
  CREATE TABLE MYDMS_VERSIONDEF
  (
  OID CHAR(32) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  SIZE1 NUMBER(9),
  SIZE2 NUMBER(9),
  DELIMITER VARCHAR2(50),
  DESCRIPTION VARCHAR2(2000),
  VALID NUMBER(9),
  CREATOR VARCHAR2(32),
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_VERSIONDEF.OID IS 'OID';
COMMENT ON COLUMN MYDMS_VERSIONDEF.NAME IS '名称';
COMMENT ON COLUMN MYDMS_VERSIONDEF.SIZE1 IS '流水号长度1';
COMMENT ON COLUMN MYDMS_VERSIONDEF.SIZE2 IS '流水号长度1';
COMMENT ON COLUMN MYDMS_VERSIONDEF.DELIMITER IS '分隔符';
COMMENT ON COLUMN MYDMS_VERSIONDEF.DESCRIPTION IS '说明';
COMMENT ON COLUMN MYDMS_VERSIONDEF.VALID IS '有效与否 0:无效, 1:有效';
COMMENT ON COLUMN MYDMS_VERSIONDEF.CREATOR IS '创建者';
COMMENT ON COLUMN MYDMS_VERSIONDEF.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_VERSIONDEF IS '自动版号定义表';



-- >>TABLE 文件夹表
CREATE TABLE MYDMS_FOLDER
(
    OID CHAR(32) PRIMARY KEY NOT NULL,
    ID NUMBER(18) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PARENT NUMBER(18),
    CREATOR VARCHAR2(32),
    CREATEDATE DATE DEFAULT SYSDATE,
    IS_EXTENDED NUMBER(9),
    IS_ADD_BY_PROCESS NUMBER(9),
    IS_UPDATE_BY_PROCESS NUMBER(9),
    IS_INVALID_BY_PROCESS NUMBER(9),
    SNRULEDEF CHAR(32),
    VERSIONDEF CHAR(32),
    PARAMETER CHAR(32),
    VALID NUMBER(9) DEFAULT 1 NOT NULL
);
COMMENT ON COLUMN MYDMS_FOLDER.OID IS 'OID';
COMMENT ON COLUMN MYDMS_FOLDER.ID IS 'ID(自增长序号)';
COMMENT ON COLUMN MYDMS_FOLDER.NAME IS '名称';
COMMENT ON COLUMN MYDMS_FOLDER.DESCRIPTION IS '说明';
COMMENT ON COLUMN MYDMS_FOLDER.PARENT IS '父文件夹ID';
COMMENT ON COLUMN MYDMS_FOLDER.CREATOR IS '创建者UserID';
COMMENT ON COLUMN MYDMS_FOLDER.CREATEDATE IS '创建日期（默认带入系统日期时间）';
COMMENT ON COLUMN MYDMS_FOLDER.IS_EXTENDED IS '是否继承父级目录配置,0:否,1:是';
COMMENT ON COLUMN MYDMS_FOLDER.IS_ADD_BY_PROCESS IS '文件上传方式, 是否通过流程上传  0:否,1:是';
COMMENT ON COLUMN MYDMS_FOLDER.IS_UPDATE_BY_PROCESS IS '文件变更方式, 是否通过流程变更  0:否,1:是';
COMMENT ON COLUMN MYDMS_FOLDER.IS_INVALID_BY_PROCESS IS '文件作废方式, 是否通过流程作废  0:否,1:是';
COMMENT ON COLUMN MYDMS_FOLDER.SNRULEDEF IS '文件编号规则OID';
COMMENT ON COLUMN MYDMS_FOLDER.VERSIONDEF IS '文件版号规则OID';
COMMENT ON COLUMN MYDMS_FOLDER.PARAMETER IS '参数定义OID';
COMMENT ON COLUMN MYDMS_FOLDER.VALID IS '文件夹状态 0:失效,1:生效';
COMMENT ON TABLE MYDMS_FOLDER IS '文件夹表';

-- 索引
CREATE INDEX IDX_MYDMS_FOLDER_PARENT ON MYDMS_FOLDER (PARENT);

-- 文件夹表ID字段自增序列
-- DROP SEQUENCE SEQ_MYDMS_FOLDER;
CREATE SEQUENCE SEQ_MYDMS_FOLDER MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE;

-- 文件夹表ID字段自增触发器
CREATE OR REPLACE TRIGGER TRIGGER_MYDMS_FOLDER
BEFORE INSERT ON MYDMS_FOLDER
FOR EACH ROW
  BEGIN
    SELECT SEQ_MYDMS_FOLDER.NEXTVAL
    INTO :NEW.ID
    FROM DUAL;
  END;



-- >>TABLE 文件信息表
CREATE TABLE MYDMS_DOCUMENT
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  SERIALNUMBER VARCHAR2(100) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  VERSION VARCHAR2(50) NOT NULL,
  AUTHOR VARCHAR2(100),
  CREATOR VARCHAR2(32),
  CREATORNAME VARCHAR2(100),
  CREATEDATE DATE DEFAULT SYSDATE,
  EFFECTIVEDATE DATE NOT NULL,
  EXPIRATIONDATE DATE NOT NULL,
  CONFIDENTIAL_LEVEL NUMBER(9) NOT NULL,
  ISTOP NUMBER(9) DEFAULT 0,
  IS_RETRIEVAL NUMBER(9),
  IS_REMIND NUMBER(9),
  TAG VARCHAR2(100),
  SUMMARY VARCHAR2(4000),
  STATUS NUMBER(9),
  FOLDER CHAR(32),
  FOLDERNAME VARCHAR2(50),
  CONSTRAINT DOC_UNIQUE_SN UNIQUE (SERIALNUMBER) -- serialnumber 添加唯一约束
  -- CONSTRAINT FK_DOCUMENT_FOLDER FOREIGN KEY (FOLDER) REFERENCES MYDMS_FOLDER (OID)
);
COMMENT ON COLUMN MYDMS_DOCUMENT.OID IS 'OID';
COMMENT ON COLUMN MYDMS_DOCUMENT.SERIALNUMBER IS '文件编号（自动生成或者手动输入）';
COMMENT ON COLUMN MYDMS_DOCUMENT.NAME IS '名称';
COMMENT ON COLUMN MYDMS_DOCUMENT.VERSION IS '版号';
COMMENT ON COLUMN MYDMS_DOCUMENT.AUTHOR IS '作者';
COMMENT ON COLUMN MYDMS_DOCUMENT.CREATOR IS '发布者UserID';
COMMENT ON COLUMN MYDMS_DOCUMENT.CREATORNAME IS '发布者UserName';
COMMENT ON COLUMN MYDMS_DOCUMENT.CREATEDATE IS '发布日期（默认带入系统日期时间）';
COMMENT ON COLUMN MYDMS_DOCUMENT.EFFECTIVEDATE IS '生效日期';
COMMENT ON COLUMN MYDMS_DOCUMENT.EXPIRATIONDATE IS '失效日期';
COMMENT ON COLUMN MYDMS_DOCUMENT.CONFIDENTIAL_LEVEL IS '机密等级 1.机密  2.公开';
COMMENT ON COLUMN MYDMS_DOCUMENT.ISTOP IS '置顶 0:否,大于0表示置顶,数字越大越靠前, 默认为0';
COMMENT ON COLUMN MYDMS_DOCUMENT.IS_RETRIEVAL IS '允许调阅 0:否,1:是';
COMMENT ON COLUMN MYDMS_DOCUMENT.IS_REMIND IS '到期提醒 0:否,1:是';
COMMENT ON COLUMN MYDMS_DOCUMENT.TAG IS '标签/关键字';
COMMENT ON COLUMN MYDMS_DOCUMENT.SUMMARY IS '摘要';
COMMENT ON COLUMN MYDMS_DOCUMENT.STATUS IS '文件状态 1为现行生效文件，2为现行未生效文件，3为历史文件，4为作废文件';
COMMENT ON COLUMN MYDMS_DOCUMENT.FOLDER IS '文件夹OID';
COMMENT ON COLUMN MYDMS_DOCUMENT.FOLDERNAME IS '文件名';
COMMENT ON TABLE MYDMS_DOCUMENT IS '文件信息表';

-- 索引
CREATE INDEX IDX_MYDMS_DOCUMENT_FOLDER ON MYDMS_DOCUMENT (FOLDER);



-- >>TABLE 文件状态锁定表
CREATE TABLE MYDMS_STATUSLOCK
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  DOCUMENT CHAR(32) NOT NULL,
  STATUS NUMBER(9) NOT NULL,
  TYPE NUMBER(9) NOT NULL,
  USERID VARCHAR2(32)
  -- CONSTRAINT FK_STATUSLOCK_DOCUMENT FOREIGN KEY (DOCUMENT) REFERENCES MYDMS_DOCUMENT (OID)
);
COMMENT ON COLUMN MYDMS_STATUSLOCK.OID IS 'OID';
COMMENT ON COLUMN MYDMS_STATUSLOCK.DOCUMENT IS '被锁定的文件';
COMMENT ON COLUMN MYDMS_STATUSLOCK.STATUS IS '状态码 0:正在进行,1:已完成';
COMMENT ON COLUMN MYDMS_STATUSLOCK.TYPE IS '修改类型 0:修改申请单,1:作废申请单';
COMMENT ON COLUMN MYDMS_STATUSLOCK.USERID IS '添加人员';
COMMENT ON TABLE MYDMS_STATUSLOCK IS '文件状态锁定表';

-- 索引
CREATE INDEX IDX_STATUSLOCK_DOCUMENT ON MYDMS_STATUSLOCK (DOCUMENT);
CREATE INDEX IDX_STATUSLOCK_USERID ON MYDMS_STATUSLOCK (USERID);



-- >>TABLE 文件调阅记录表
CREATE TABLE MYDMS_RETRIEVALRECORD
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  DOCUMENT CHAR(32) NOT NULL,
  RETRIEVEDATE DATE DEFAULT SYSDATE,
  USERID VARCHAR2(32) NOT NULL,
  STATUS NUMBER(9) NOT NULL
  -- CONSTRAINT FK_RETRIEVALRECORD_DOCUMENT FOREIGN KEY (DOCUMENT) REFERENCES MYDMS_DOCUMENT (OID)
);
COMMENT ON COLUMN MYDMS_RETRIEVALRECORD.OID IS 'OID';
COMMENT ON COLUMN MYDMS_RETRIEVALRECORD.DOCUMENT IS '调阅文件';
COMMENT ON COLUMN MYDMS_RETRIEVALRECORD.RETRIEVEDATE IS '调阅日期';
COMMENT ON COLUMN MYDMS_RETRIEVALRECORD.USERID IS '调阅人员';
COMMENT ON COLUMN MYDMS_RETRIEVALRECORD.STATUS IS '调阅状态 0:申请失败（暂时没有用上）, 1:申请中, 2:申请成功';
COMMENT ON TABLE MYDMS_STATUSLOCK IS '文件调阅记录表';

-- 索引
CREATE INDEX IDX_RETRIEVALRECORD_DOCUMENT ON MYDMS_RETRIEVALRECORD (DOCUMENT);
CREATE INDEX IDX_RETRIEVALRECORD_USERID ON MYDMS_RETRIEVALRECORD (USERID);



-- >>TABLE 文件变更记录表
CREATE TABLE MYDMS_CHANGERECORD
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  CHANGEBY VARCHAR2(50),
  CHANGEDATE DATE DEFAULT SYSDATE,
  DOCUMENT CHAR(32)
  -- CONSTRAINT FK_CHANGE_DOCUMENT FOREIGN KEY (DOCUMENT) REFERENCES MYDMS_DOCUMENT (OID)
);
COMMENT ON COLUMN MYDMS_CHANGERECORD.OID IS 'OID';
COMMENT ON COLUMN MYDMS_CHANGERECORD.DESCRIPTION IS '变更说明';
COMMENT ON COLUMN MYDMS_CHANGERECORD.CHANGEBY IS '变更人';
COMMENT ON COLUMN MYDMS_CHANGERECORD.CHANGEDATE IS '变更日期';
COMMENT ON COLUMN MYDMS_CHANGERECORD.DOCUMENT IS '所属文件(文件OID)';
COMMENT ON TABLE MYDMS_CHANGERECORD IS '文件变更记录表';

-- 索引
CREATE INDEX IDX_MYDMS_CHANGE_DOCUMENT ON MYDMS_CHANGERECORD (DOCUMENT);



-- >>TABLE 附件信息表
CREATE TABLE MYDMS_ATTACHMENT
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  TYPE VARCHAR2(50),
  CREATOR VARCHAR2(32),
  CREATEDATE DATE DEFAULT SYSDATE,
  FILESIZE NUMBER(18),
  IS_REFERENCE NUMBER(9),
  DOCUMENT CHAR(32)
  -- CONSTRAINT FK_ATTACHMENT_DOCUMENT FOREIGN KEY (DOCUMENT) REFERENCES MYDMS_DOCUMENT (OID)
);
COMMENT ON COLUMN MYDMS_ATTACHMENT.OID IS 'OID';
COMMENT ON COLUMN MYDMS_ATTACHMENT.NAME IS '文件名';
COMMENT ON COLUMN MYDMS_ATTACHMENT.TYPE IS '类型,后缀名';
COMMENT ON COLUMN MYDMS_ATTACHMENT.CREATOR IS '上传者';
COMMENT ON COLUMN MYDMS_ATTACHMENT.CREATEDATE IS '上传日期';
COMMENT ON COLUMN MYDMS_ATTACHMENT.FILESIZE IS '附件大小';
COMMENT ON COLUMN MYDMS_ATTACHMENT.IS_REFERENCE IS '是否为参考文件 1:是, 0:否';
COMMENT ON COLUMN MYDMS_ATTACHMENT.DOCUMENT IS '所属文件(文件OID)';
COMMENT ON TABLE MYDMS_ATTACHMENT IS '附件信息表';

-- 索引
CREATE INDEX IDX_MYDMS_ATTACHMENT_DOCUMENT ON MYDMS_ATTACHMENT (DOCUMENT);


-- >>TABLE 附件（临时文件）信息表
CREATE TABLE MYDMS_TEMPFILE
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  TYPE VARCHAR2(50),
  CREATOR VARCHAR2(32),
  CREATEDATE DATE DEFAULT SYSDATE,
  CONTENTTYPE VARCHAR2(200),
  FILESIZE NUMBER(18),
  URL VARCHAR2(300),
  DELETEURL VARCHAR2(300),
  FOLDER CHAR(32),
  STAT NUMBER(9)
);
COMMENT ON COLUMN MYDMS_TEMPFILE.OID IS 'OID';
COMMENT ON COLUMN MYDMS_TEMPFILE.NAME IS '文件名';
COMMENT ON COLUMN MYDMS_TEMPFILE.TYPE IS '类型,后缀名';
COMMENT ON COLUMN MYDMS_TEMPFILE.CREATOR IS '上传者';
COMMENT ON COLUMN MYDMS_TEMPFILE.CREATEDATE IS '上传日期';
COMMENT ON COLUMN MYDMS_TEMPFILE.CONTENTTYPE IS '类型';
COMMENT ON COLUMN MYDMS_TEMPFILE.FILESIZE IS '文件大小';
COMMENT ON COLUMN MYDMS_TEMPFILE.URL IS '下载链接';
COMMENT ON COLUMN MYDMS_TEMPFILE.DELETEURL IS '删除链接';
COMMENT ON COLUMN MYDMS_TEMPFILE.FOLDER IS '文件夹OID';
COMMENT ON COLUMN MYDMS_TEMPFILE.STAT IS '状态 1:有效，0:无效';
COMMENT ON TABLE MYDMS_TEMPFILE IS '附件（临时文件）信息表';

-- 索引
CREATE INDEX IDX_MYDMS_TEMPFILE_FOLDER ON MYDMS_TEMPFILE (FOLDER);



-- >>TABLE 角色表
CREATE TABLE MYDMS_ROLE
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  TYPE NUMBER(9),
  VALID NUMBER(9),
  CREATOR VARCHAR2(32),
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_ROLE.OID IS 'OID';
COMMENT ON COLUMN MYDMS_ROLE.NAME IS '角色名';
COMMENT ON COLUMN MYDMS_ROLE.DESCRIPTION IS '描述';
COMMENT ON COLUMN MYDMS_ROLE.TYPE IS '角色类型 0:文件管理员, 1:目录管理员';
COMMENT ON COLUMN MYDMS_ROLE.VALID IS '有效与否 0:无效, 1:有效';
COMMENT ON COLUMN MYDMS_ROLE.CREATOR IS '创建者';
COMMENT ON COLUMN MYDMS_ROLE.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_ROLE IS '角色表';



-- >>TABLE 权限表
CREATE TABLE MYDMS_PERMISSION
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  PERMISSION VARCHAR2(50) NOT NULL
);
COMMENT ON COLUMN MYDMS_PERMISSION.OID IS 'OID';
COMMENT ON COLUMN MYDMS_PERMISSION.NAME IS '权限名';
COMMENT ON COLUMN MYDMS_PERMISSION.PERMISSION IS '权限';
COMMENT ON TABLE MYDMS_PERMISSION IS '权限表';



-- >>TABLE 角色_权限表
CREATE TABLE MYDMS_ROLE_PERMISSION
(
  -- OID CHAR(32) PRIMARY KEY NOT NULL,
  ROLE CHAR(32) NOT NULL,
  PERMISSION CHAR(32) NOT NULL
  -- CONSTRAINT FK_ROLE_PERMISSION_ROLE FOREIGN KEY (ROLE) REFERENCES MYDMS_ROLE (OID),
  -- CONSTRAINT FK_ROLE_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION) REFERENCES MYDMS_PERMISSION (OID)
);
-- COMMENT ON COLUMN MYDMS_ROLE_PERMISSION.OID IS 'OID';
COMMENT ON COLUMN MYDMS_ROLE_PERMISSION.ROLE IS '对应角色OID';
COMMENT ON COLUMN MYDMS_ROLE_PERMISSION.PERMISSION IS '对应权限OID';
COMMENT ON TABLE MYDMS_ROLE_PERMISSION IS '角色_权限表';



-- >>TABLE 角色_文件夹表
CREATE TABLE MYDMS_ROLE_FOLDER
(
  -- OID CHAR(32) PRIMARY KEY NOT NULL,
  ROLE CHAR(32) NOT NULL,
  FOLDER CHAR(32) NOT NULL
  -- CONSTRAINT FK_ROLE_FOLDER_ROLE FOREIGN KEY (ROLE) REFERENCES MYDMS_ROLE (OID),
  -- CONSTRAINT FK_ROLE_FOLDER_FOLDER FOREIGN KEY (FOLDER) REFERENCES MYDMS_FOLDER (OID)
);
-- COMMENT ON COLUMN MYDMS_ROLE_FOLDER.OID IS 'OID';
COMMENT ON COLUMN MYDMS_ROLE_FOLDER.ROLE IS '对应角色OID';
COMMENT ON COLUMN MYDMS_ROLE_FOLDER.FOLDER IS '对应文件夹OID';
COMMENT ON TABLE MYDMS_ROLE_FOLDER IS '角色_文件夹表';

-- 索引
CREATE INDEX IDX_MYDMS_ROLE_FOLDER_ROLE ON MYDMS_ROLE_FOLDER (ROLE);
CREATE INDEX IDX_MYDMS_ROLE_FOLDER_FOLDER ON MYDMS_ROLE_FOLDER (FOLDER);



-- >>TABLE 用户_角色表
CREATE TABLE MYDMS_USERS_ROLE
(
  USERS VARCHAR2(50) NOT NULL,
  ROLE CHAR(32) NOT NULL
);
COMMENT ON COLUMN MYDMS_USERS_ROLE.USERS IS '对应用户(每条记录只插入一笔用户,多用户则生成多条记录) U_00001:表示对应的是User, D_00001:表示对应的是Department, G_00001:表示对应的是Group';
COMMENT ON COLUMN MYDMS_USERS_ROLE.ROLE IS '对应角色OID';
COMMENT ON TABLE MYDMS_USERS_ROLE IS '用户_角色表';

-- 索引
CREATE INDEX IDX_MYDMS_USERS_ROLE_ROLE ON MYDMS_USERS_ROLE (ROLE);



-- >>TABLE DMS申请状态表
CREATE TABLE MYDMS_DOCREQUISITION
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  FOLDER CHAR(32) NOT NULL,
  DOCUMENT CHAR(32),
  REQUESTTYPE NUMBER(9),
  USERID VARCHAR2(32) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE,
  ADMIN VARCHAR2(2000)
);
COMMENT ON COLUMN MYDMS_DOCREQUISITION.OID IS 'OID';
COMMENT ON COLUMN MYDMS_DOCREQUISITION.FOLDER IS '文件夹OID';
COMMENT ON COLUMN MYDMS_DOCREQUISITION.DOCUMENT IS 'Document OID 类型为DMS新增申请单的时候，该记录为null';
COMMENT ON COLUMN MYDMS_DOCREQUISITION.REQUESTTYPE IS '请求的文件类型, 0_新增;1_修改;2_作废;3_调阅(调阅类型暂时没用上))';
COMMENT ON COLUMN MYDMS_DOCREQUISITION.USERID IS '申请人UserId';
COMMENT ON COLUMN MYDMS_DOCREQUISITION.CREATEDATE IS '创建日期（默认带入系统日期时间）';
COMMENT ON COLUMN MYDMS_DOCREQUISITION.ADMIN IS '管理员UserId（;分隔）';
COMMENT ON TABLE MYDMS_DOCREQUISITION IS 'DMS申请状态表';



-- 》》》》》》》》》》》》》》》
-- >>REPORT报表相关

-- >>TABLE  文件查看记录
CREATE TABLE MYDMS_REPORT_VIEW
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  Document CHAR(32) NOT NULL,
  DocumentName VARCHAR2(100),
  Folder CHAR(32),
  FolderName VARCHAR2(100),
  UserId VARCHAR2(32) NOT NULL,
  UserName VARCHAR2(50) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_REPORT_VIEW.OID IS 'OID';
COMMENT ON COLUMN MYDMS_REPORT_VIEW.Document IS '文件OID';
COMMENT ON COLUMN MYDMS_REPORT_VIEW.DocumentName IS '文件名';
COMMENT ON COLUMN MYDMS_REPORT_VIEW.Folder IS '文件夹OID';
COMMENT ON COLUMN MYDMS_REPORT_VIEW.FolderName IS '文件夹名';
COMMENT ON COLUMN MYDMS_REPORT_VIEW.UserId IS 'userId';
COMMENT ON COLUMN MYDMS_REPORT_VIEW.UserName IS 'userName';
COMMENT ON COLUMN MYDMS_REPORT_VIEW.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_REPORT_VIEW IS '文件查看记录';

-- 索引
CREATE INDEX IDX_MYDMS_REPORT_VIEW_Document ON MYDMS_REPORT_VIEW (DocumentName);
CREATE INDEX IDX_MYDMS_REPORT_VIEW_Folder ON MYDMS_REPORT_VIEW (FolderName);
CREATE INDEX IDX_MYDMS_REPORT_VIEW_User ON MYDMS_REPORT_VIEW (UserName);
CREATE INDEX IDX_MYDMS_REPORT_VIEW_CREDATE ON MYDMS_REPORT_VIEW (CREATEDATE);




-- >>TABLE  文件新增记录
CREATE TABLE MYDMS_REPORT_NEW
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  Document CHAR(32) NOT NULL,
  DocumentName VARCHAR2(100),
  Folder CHAR(32),
  FolderName VARCHAR2(100),
  UserId VARCHAR2(32) NOT NULL,
  UserName VARCHAR2(50) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_REPORT_NEW.OID IS 'OID';
COMMENT ON COLUMN MYDMS_REPORT_NEW.Document IS '文件OID';
COMMENT ON COLUMN MYDMS_REPORT_NEW.DocumentName IS '文件名';
COMMENT ON COLUMN MYDMS_REPORT_NEW.Folder IS '文件夹OID';
COMMENT ON COLUMN MYDMS_REPORT_NEW.FolderName IS '文件夹名';
COMMENT ON COLUMN MYDMS_REPORT_NEW.UserId IS 'userId';
COMMENT ON COLUMN MYDMS_REPORT_NEW.UserName IS 'userName';
COMMENT ON COLUMN MYDMS_REPORT_NEW.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_REPORT_NEW IS '文件新增记录';

-- 索引
CREATE INDEX IDX_MYDMS_REPORT_NEW_Document ON MYDMS_REPORT_NEW (DocumentName);
CREATE INDEX IDX_MYDMS_REPORT_NEW_Folder ON MYDMS_REPORT_NEW (FolderName);
CREATE INDEX IDX_MYDMS_REPORT_NEW_User ON MYDMS_REPORT_NEW (UserName);
CREATE INDEX IDX_MYDMS_REPORT_NEW_CREDATE ON MYDMS_REPORT_NEW (CREATEDATE);



-- >>TABLE  文件修改记录
CREATE TABLE MYDMS_REPORT_MODIFY
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  Document CHAR(32) NOT NULL,
  DocumentName VARCHAR2(100),
  Folder CHAR(32),
  FolderName VARCHAR2(100),
  UserId VARCHAR2(32) NOT NULL,
  UserName VARCHAR2(50) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.OID IS 'OID';
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.Document IS '文件OID';
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.DocumentName IS '文件名';
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.Folder IS '文件夹OID';
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.FolderName IS '文件夹名';
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.UserId IS 'userId';
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.UserName IS 'userName';
COMMENT ON COLUMN MYDMS_REPORT_MODIFY.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_REPORT_MODIFY IS '文件修改记录';

-- 索引
CREATE INDEX IDX_MYDMS_REPORT_MOD_Document ON MYDMS_REPORT_MODIFY (DocumentName);
CREATE INDEX IDX_MYDMS_REPORT_MOD_Folder ON MYDMS_REPORT_MODIFY (FolderName);
CREATE INDEX IDX_MYDMS_REPORT_MOD_User ON MYDMS_REPORT_MODIFY (UserName);
CREATE INDEX IDX_MYDMS_REPORT_MOD_CREDATE ON MYDMS_REPORT_MODIFY (CREATEDATE);



-- >>TABLE  附件上传记录
CREATE TABLE MYDMS_REPORT_UPLOAD
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  Attachment CHAR(32) NOT NULL,
  AttachmentName VARCHAR2(100),
  Document CHAR(32) NOT NULL,
  DocumentName VARCHAR2(100),
  UserId VARCHAR2(32) NOT NULL,
  UserName VARCHAR2(50) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.OID IS 'OID';
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.Attachment IS '附件OID';
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.AttachmentName IS '附件名';
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.Document IS '文件OID';
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.DocumentName IS '文件名';
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.UserId IS 'userId';
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.UserName IS 'userName';
COMMENT ON COLUMN MYDMS_REPORT_UPLOAD.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_REPORT_UPLOAD IS '附件上传记录';

-- 索引
CREATE INDEX IDX_MYDMS_REPORT_UP_Attach ON MYDMS_REPORT_UPLOAD (AttachmentName);
CREATE INDEX IDX_MYDMS_REPORT_UP_Document ON MYDMS_REPORT_UPLOAD (DocumentName);
CREATE INDEX IDX_MYDMS_REPORT_UP_User ON MYDMS_REPORT_UPLOAD (UserName);
CREATE INDEX IDX_MYDMS_REPORT_UP_CREDATE ON MYDMS_REPORT_UPLOAD (CREATEDATE);



-- >>TABLE  附件下载记录
CREATE TABLE MYDMS_REPORT_DOWNLOAD
(
  OID CHAR(32) PRIMARY KEY NOT NULL,
  Attachment CHAR(32) NOT NULL,
  AttachmentName VARCHAR2(100),
  Document CHAR(32) NOT NULL,
  DocumentName VARCHAR2(100),
  UserId VARCHAR2(32) NOT NULL,
  UserName VARCHAR2(50) NOT NULL,
  CREATEDATE DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.OID IS 'OID';
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.Attachment IS '附件OID';
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.AttachmentName IS '附件名';
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.Document IS '文件OID';
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.DocumentName IS '文件名';
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.UserId IS 'userId';
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.UserName IS 'userName';
COMMENT ON COLUMN MYDMS_REPORT_DOWNLOAD.CREATEDATE IS '创建日期';
COMMENT ON TABLE MYDMS_REPORT_DOWNLOAD IS '附件下载记录';

-- 索引
CREATE INDEX IDX_MYDMS_REPORT_DOW_Attach ON MYDMS_REPORT_DOWNLOAD (AttachmentName);
CREATE INDEX IDX_MYDMS_REPORT_DOW_Document ON MYDMS_REPORT_DOWNLOAD (DocumentName);
CREATE INDEX IDX_MYDMS_REPORT_DOW_User ON MYDMS_REPORT_DOWNLOAD (UserName);
CREATE INDEX IDX_MYDMS_REPORT_DOW_CREDATE ON MYDMS_REPORT_DOWNLOAD (CREATEDATE);