-- table
DROP TABLE MYDMS_PARAMETER;
DROP TABLE MYDMS_SNRULEDEF;
DROP TABLE MYDMS_SNTEMP;
DROP TABLE MYDMS_VERSIONDEF;
DROP TABLE MYDMS_FOLDER;
DROP TABLE MYDMS_DOCUMENT;
DROP TABLE MYDMS_STATUSLOCK;
DROP TABLE MYDMS_RETRIEVALRECORD;
DROP TABLE MYDMS_CHANGERECORD;
DROP TABLE MYDMS_ATTACHMENT;
DROP TABLE MYDMS_TEMPFILE;
DROP TABLE MYDMS_ROLE;
DROP TABLE MYDMS_PERMISSION;
DROP TABLE MYDMS_ROLE_PERMISSION;
DROP TABLE MYDMS_ROLE_FOLDER;
DROP TABLE MYDMS_USERS_ROLE;
DROP TABLE MYDMS_DOCREQUISITION;
DROP TABLE MYDMS_REPORT_VIEW;
DROP TABLE MYDMS_REPORT_NEW;
DROP TABLE MYDMS_REPORT_MODIFY;
DROP TABLE MYDMS_REPORT_UPLOAD;
DROP TABLE MYDMS_REPORT_DOWNLOAD;

-- sequence
DROP SEQUENCE SEQ_MYDMS_FOLDER;