-- MYDMS ModuleDefinition
INSERT INTO ModuleDefinition(OID,objectVersion,id,name,isDefault,bundleContainer,containerOID)
VALUES('mydms29df8d44244a1ef54d3d21ab111',1,'mydms01','DMS',1,'<com.dsc.nana.domain.XMLRsrcBundleContainerImpl>
	  <bundleMap>
	    <entry>
	      <string>en_US</string>
	      <com.dsc.nana.domain.SysResourceBundle>
		<rsrcMap>
		  <entry>
		    <string>name</string>
		    <com.dsc.nana.domain.RsrcBundleValue>
		      <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
		      <labelKey>name</labelKey>
		      <languageOID>en_US</languageOID>
		      <labelValue>common document</labelValue>
		      <description></description>
		      <labelHint></labelHint>
		      <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
		      <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
		      <dto>true</dto>
		      <dtoState>
			<value>0</value>
		      </dtoState>
		      <objectVersion>0</objectVersion>
		    </com.dsc.nana.domain.RsrcBundleValue>
		  </entry>
		</rsrcMap>
	      </com.dsc.nana.domain.SysResourceBundle>
	    </entry>
	    <entry>
	      <string>zh_TW</string>
	      <com.dsc.nana.domain.SysResourceBundle>
		<rsrcMap>
		  <entry>
		    <string>name</string>
		    <com.dsc.nana.domain.RsrcBundleValue>
		      <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
		      <labelKey>name</labelKey>
		      <languageOID>zh_TW</languageOID>
		      <labelValue>MYDMS</labelValue>
		      <description></description>
		      <labelHint></labelHint>
		      <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
		      <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
		      <dto>true</dto>
		      <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
		      <objectVersion>0</objectVersion>
		    </com.dsc.nana.domain.RsrcBundleValue>
		  </entry>
		</rsrcMap>
	      </com.dsc.nana.domain.SysResourceBundle>
	    </entry>
	    <entry>
	      <string>zh_CN</string>
	      <com.dsc.nana.domain.SysResourceBundle>
		<rsrcMap>
		  <entry>
		    <string>name</string>
		    <com.dsc.nana.domain.RsrcBundleValue>
		      <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
		      <labelKey>name</labelKey>
		      <languageOID>zh_CN</languageOID>
		      <labelValue>MYDMS</labelValue>
		      <description></description>
		      <labelHint></labelHint>
		      <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
		      <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
		      <dto>true</dto>
		      <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
		      <objectVersion>0</objectVersion>
		    </com.dsc.nana.domain.RsrcBundleValue>
		  </entry>
		</rsrcMap>
	      </com.dsc.nana.domain.SysResourceBundle>
	    </entry>
	  </bundleMap>
	  <bundleClass>com.dsc.nana.domain.module.ProgramDefinition</bundleClass>
	</com.dsc.nana.domain.XMLRsrcBundleContainerImpl>'
	,'');


-- 设置
insert into ProgramDefinition (OID, objectVersion, id, name, linkUrl, isDefault, bundleContainer, containerOID, urlType) values ('mydms244a1ef5444a1ef54d3d21ab111', 1, 'mydmsparameter', '设置', '/bpm-dms/docParameter?userId=<#userId>', 1, '<com.dsc.nana.domain.XMLRsrcBundleContainerImpl>
  <bundleMap>
    <entry>
      <string>en_US</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>en_US</languageOID>
              <labelValue>Access to document</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState>
                <value>0</value>
              </dtoState>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_TW</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_TW</languageOID>
              <labelValue>设置</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_CN</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_CN</languageOID>
              <labelValue>设置</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
  </bundleMap>
  <bundleClass>com.dsc.nana.domain.module.ModuleDefinition</bundleClass>
</com.dsc.nana.domain.XMLRsrcBundleContainerImpl>', 'mydms29df8d44244a1ef54d3d21ab111', 0);


-- 文件树页面
insert into ProgramDefinition (OID, objectVersion, id, name, linkUrl, isDefault, bundleContainer, containerOID, urlType) values ('mydms244a1ef5444a1ef54d3d21ab222', 1, 'mydmstree', '文件树', '/bpm-dms/login/tree/<#userId>', 1, '<com.dsc.nana.domain.XMLRsrcBundleContainerImpl>
  <bundleMap>
    <entry>
      <string>en_US</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>en_US</languageOID>
              <labelValue>Access to document</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState>
                <value>0</value>
              </dtoState>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_TW</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_TW</languageOID>
              <labelValue>文件树</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_CN</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_CN</languageOID>
              <labelValue>文件树</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
  </bundleMap>
  <bundleClass>com.dsc.nana.domain.module.ModuleDefinition</bundleClass>
</com.dsc.nana.domain.XMLRsrcBundleContainerImpl>', 'mydms29df8d44244a1ef54d3d21ab111', 0);


-- 报表
insert into ProgramDefinition (OID, objectVersion, id, name, linkUrl, isDefault, bundleContainer, containerOID, urlType) values ('mydms244a1ef5444a1ef54d3d21ab333', 1, 'mydmsreports', '报表', '/bpm-dms/reports', 1, '<com.dsc.nana.domain.XMLRsrcBundleContainerImpl>
  <bundleMap>
    <entry>
      <string>en_US</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>en_US</languageOID>
              <labelValue>Access to document</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState>
                <value>0</value>
              </dtoState>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_TW</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_TW</languageOID>
              <labelValue>报表</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_CN</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_CN</languageOID>
              <labelValue>报表</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
  </bundleMap>
  <bundleClass>com.dsc.nana.domain.module.ModuleDefinition</bundleClass>
</com.dsc.nana.domain.XMLRsrcBundleContainerImpl>', 'mydms29df8d44244a1ef54d3d21ab111', 0);


-- 高级查询
insert into ProgramDefinition (OID, objectVersion, id, name, linkUrl, isDefault, bundleContainer, containerOID, urlType) values ('mydms244a1ef5444a1ef54d3d21ab444', 1, 'mydmssearch', '搜索', '/bpm-dms/login/search/<#userId>', 1, '<com.dsc.nana.domain.XMLRsrcBundleContainerImpl>
  <bundleMap>
    <entry>
      <string>en_US</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>en_US</languageOID>
              <labelValue>Access to document</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState>
                <value>0</value>
              </dtoState>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_TW</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_TW</languageOID>
              <labelValue>搜索</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
    <entry>
      <string>zh_CN</string>
      <com.dsc.nana.domain.SysResourceBundle>
        <rsrcMap>
          <entry>
            <string>name</string>
            <com.dsc.nana.domain.RsrcBundleValue>
              <programId>com.dsc.nana.domain.XMLRsrcBundleContainerImpl</programId>
              <labelKey>name</labelKey>
              <languageOID>zh_CN</languageOID>
              <labelValue>搜索</labelValue>
              <description></description>
              <labelHint></labelHint>
              <SET__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.SetProxy</SET__PROXY__CLASS__NAME>
              <LIST__PROXY__CLASS__NAME>org.apache.ojb.broker.accesslayer.ListProxy</LIST__PROXY__CLASS__NAME>
              <dto>true</dto>
              <dtoState reference="../../../../../../entry/com.dsc.nana.domain.SysResourceBundle/rsrcMap/entry/com.dsc.nana.domain.RsrcBundleValue/dtoState"/>
              <objectVersion>0</objectVersion>
            </com.dsc.nana.domain.RsrcBundleValue>
          </entry>
        </rsrcMap>
      </com.dsc.nana.domain.SysResourceBundle>
    </entry>
  </bundleMap>
  <bundleClass>com.dsc.nana.domain.module.ModuleDefinition</bundleClass>
</com.dsc.nana.domain.XMLRsrcBundleContainerImpl>', 'mydms29df8d44244a1ef54d3d21ab111', 0);